### PR TITLE
Updated to PCL Profile 256

### PR DESCRIPTION
**Pull request by colincnash**
Updated the main dll to PCL profile 256 and fixed codebase to use new reflection API's

### CODE REVIEW

**Comment by seesharper** [comment]
I guess you mean 259 rather than 256? :)

**Comment by colincnash** [comment]
Sorry! Yep it's 259. I've not decided to go inventing my own profiles just yet.

**Comment by StevenLiekens** [comment]
Any update on this? I'm trying to use LightMock in a portable-net45+win+wpa81 assembly, but it's not currently supported.

**Comment by andrewesweet** [comment]
I've applied this PR as a patch locally and it's working well for me.

**Comment by seesharper** [comment]
This project has moved to `netstandard2.0` 👍🎂

**Pull request closed without merging**
