### PR TITLE
Uwp support

### PR DESCRIPTION
**Pull request by anton-yashin**
Hi! Changes due #14 latest UWP SDK's doesn't work properly with netstandard 1.0:
* LightMock target framework updated to netstandard2.0
* LightMock.Tests target framework updated to netcoreapp3.1
* tests migrated to xunit
* added test runners for android, ios and uwp platforms.

If there too many changes i can just update frameworks.

Thanks.

### CODE REVIEW

**Comment by anton-yashin** [comment]
Hmm. No vs2017rc at appveyor. May be i need to make changes in appveyor.yml?

**Comment by seesharper** [comment]
I guess it is about time to update the build for this project :) I'll take a look at it

**Comment by seesharper** [comment]
Hi @anton-yashin and thanks a lot for your work migrating the tests to xUnit.
I have however decided to just bump to `netstandard2.0` and leaving out the tests that specifically targets the various platforms.
`netstandard2.0` is supported by all these platforms so there should not be any need to test this.
But again, thanks a lot for your work

**Comment by anton-yashin** [comment]
Thanks :-)

**Pull request closed without merging**
